### ISSUE TITLE
How to play publish RTMP stream on VLC or other player?

### ISSUE THREAD

**Issue by wasimsafdar** [shogo4405/lf.swift#118]
How can I play RTMP live stream on VLC and flash player after publishing it on local network? I tried but it always fails.

My URL streamed link is as follows:
rtmp://[local-IPAddress]/trainer/live1/streamName

**Comment by wasimsafdar** [comment]
If I use RTMP server and online player, then I am able to stream. For example, if  url mentioned in following online player. http://raspi.monaserver.ovh/MonaClients/VideoPlayer/. I also stream the video using RTSP protocol but for it you do not need any server. Also, it is mentioned in documentation that we can use localhost. Is their any need of replay kit in the app to view live streaming?

**Comment by sherm4n90** [comment]
@wasimsafdar If you need it on iOS you can try PLPlayerKit here https://github.com/pili-engineering/PLPlayerKit

**Comment by shogo4405** [comment]
I'm not sure. "RTMP URL parse" is player specific.
For example, http://videojs.com/ is
rtmp://[local-IPAddress]/trainer/live1/**&**streamName

**Comment by sfaxon** [comment]
I've got VLC playback to work with HaishinKit. The problem seems to be with this line:
https://github.com/shogo4405/HaishinKit.swift/blob/978f87901b4e61e26c779bcfac0e12e3f432eeb0/Sources/RTMP/RTMPMuxer.swift#L66-L71

Coming off of the camera `sampleBuffer.decodeTimeStamp` is always `kCMTimeInvalid` so `compositionTime` is always zero. Even if the sampleBuffer had a decodeTimeStamp line 70 is:
`compositionTime = Int32((decodeTimeStamp.seconds - decodeTimeStamp.seconds) * 1000)`
I can't see any way that this value would be non-zero. 

I created a pull request to fix this that is linked above.
