### ISSUE TITLE
Adaptive bitrate streaming 

### ISSUE THREAD

**Issue by pinkladywithcoco** [shogo4405/lf.swift#126]
Any chance to add Adaptive Bitrate support??

**Comment by pvinis** [comment]
so 0.5.12 is out. is adaptive bitrate in there? i dont see how this commit adds that.

**Comment by omarojo** [comment]
@shogo4405 How do you activate Adaptive Bitrate in the latest version of the library? I dont see that support either.

**Comment by shogo4405** [comment]
1.  Automatic drop frames
    -  https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPStream.swift#L660
1.  Handling
    - https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPStreamQoSDelagate.swift
   - Detect  upload insufficent BandWidth algorithm is here: https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L407-L418

```
class MyRTMPStreamQoSDelagate: RTMPStreamQoSDelagate {
    var bitrate = 1024 * 1024 * 8

    // detect upload insufficent BandWidth
    func didPublishInsufficientBW(_ stream:RTMPStream, withConnection:RTMPConnection) {
          bitrate = bitrate / 2
          stream.videoSettings["bitrate"] = bitrate
    }

    func clear() {
          bitreate = 1024 * 1024 * 8
    }
}

var rtmpStream = RTMPStream(~)
rtmpStream.qosDelegate = MyRTMPStreamQoSDelagate()

```

**Comment by omarojo** [comment]
@shogo4405 Thank you very much for writing an example. 👍 

I see that the bitrate is divided by 2 when there is a bad connection.
But what happens when the connection becomes GOOD again? how do you augment the bitrate again?
Is clear() called when the connectivity becomes stable ? I see it only gets called in the .open state of the stream. https://github.com/shogo4405/lf.swift/blob/f97728bd91aca1fcfef2ef8f7e1940d7745b9e85/Sources/RTMP/RTMPStream.swift#L239

**Comment by MingLoan** [comment]
@omarojo 
How do you solve the situation than the network becomes good again ?!

**Comment by milesegan** [comment]
@MingLoan I guess you would have to do something like run a timer and check to see if you haven't received any more low bandwidth warnings in a certain time interval. If not, you could try increasing the bandwidth again.

**Comment by allenlinli** [comment]
The link of the handling part does not work anymore.
[https://github.com/shogo4405/lf.swift/blob/master/Sources/RTMP/RTMPStreamQoSDelagate.swift]

**Comment by pinkfish** [comment]
Looking at this and I added it according to all the instructions, but the bitrate doesn't actually seem to be changing from what I can tell?  I get the callback, update the value but next time I get the callback the bitrate is the original value.  Doesn't seem to be changing?

**Comment by ArchForge** [comment]
I've also implemented the delegate, but it still seems to be only the frame rate that changes when BW drops. I'm logging the rtmpConnection.currentBytesOutPerSecond, but that never decreases. The in/sufficientBW functions are being called as expected.

I have seen occasional bitrate drops (bitrate + framerate drop) in some live tests (going down in a basement etc.), but when testing with network link conditioner, it seems to only ever reduce the framerate.

Possible causes off the top of my head:
I've left the clear() function empty because I'm not sure what it does. I haven't overridden didOutputAudio , didOutputVideo or didStatics. Do you have to do a reconnect after changing the bitrate for it to take effect? My implementation is using version 1.0.9, I use .requireNetworkFramework and I use a custom VideoEffect() as an overlay.

**Comment by ArungokulPersonal** [comment]
@pinkfish Can I know where are you fetching the bitrate from while using the RTMPStreamDelegate methods?

**Comment by GeneticGenesis** [comment]
https://github.com/shogo4405/HaishinKit.swift/issues/787#issuecomment-735883389

The updated implementation is here. 

Thanks.
