### ISSUE TITLE
Torch gets blown out on orientation change

### ISSUE THREAD

**Issue by jackfreed** [shogo4405/lf.swift#190]
anybody try that?

**Comment by mzmiric5** [comment]
yeah, I've noticed the same issue. I believe it's caused by the fact that the rotation change causes a camera re-instance (which is why u get a short stutter, rather than just a smooth transition). I've gotten around it by just keeping track of the torch status in a separate variable, and on rotation, I check if I'm currently using a back camera and if the torch is on. If it is on, I turn it off and on again, which causes a short flash but keeps the torch on as an end result.

It's probably possible to resolve this on framework end, but it might have to do with how the camera rotation is handled.

**Comment by shogo4405** [comment]
Thank u. Feedback. I will try to fix. :)

**Comment by shogo4405** [comment]
I fixed it. But turn off a torch in a moment. This timing... https://github.com/shogo4405/lf.swift/commit/f0611759c189c5da0ef920ead183c18d2c6cff4a#diff-cecc9d90c99061e129503b083697d6caR63

anybody, Do you know a good solution?
